;;; editor-completion-graphical.el --- Corfu draft documentation check -*- lexical-binding: t; -*-
(require 'isled-editor)
(require 'corfu)
(require 'corfu-popupinfo)
(condition-case failure
    (let ((file (make-temp-file "isled-preview-body-")))
      (with-temp-file file (insert "Issue documentation from the ledger."))
      (switch-to-buffer (get-buffer-create "*Editor completion check*"))
      (isled-editor-mode)
      (setq isled-editor-root temporary-file-directory isled-editor-validation-delay 1000)
      (isled-editor-form-render (isled-editor-empty-draft))
      (setq isled-editor-candidates (list (isled-issue-create :id "0002" :title "Widget validation" :status "open" :path file)
                                          (isled-issue-create :id "0003" :title "Widget display" :status "open" :path file)))
      (corfu-mode 1)
      (corfu-popupinfo-mode -1)
      (setq isled-editor-choices '("k:bug" "k:feature" "t:hello" "t:coucou"))
      (let ((draft (isled-editor-empty-draft)))
        (setf (alist-get 'kind draft) "")
        (isled-editor-form-render draft))
      (execute-kbd-macro (kbd "C-<tab> TAB"))
      (unless (member "feature" corfu--candidates)
        (error "Empty Kind did not offer existing kinds"))
      (corfu-quit)
      (execute-kbd-macro (kbd "C-<tab> TAB"))
      (unless (member "hello" corfu--candidates)
        (error "Empty Tags was skipped or did not offer existing tags"))
      (corfu-quit)
      (goto-char (widget-field-start (cdr (assoc "statement" isled-editor-fields))))
      (insert "#Widget")
      (execute-kbd-macro (kbd "TAB"))
      (unless corfu--candidates (error "No Corfu issue candidates"))
      (unless (seq-some (lambda (s) (string-match-p "Widget" s)) corfu--candidates)
        (error "Title matching failed"))
      (unless (not corfu-popupinfo-mode) (error "Preview mode was overridden"))
      (when isled-editor-documents (error "Disabled preview loaded documentation"))
      (corfu-next)
      (corfu-popupinfo-mode 1)
      (corfu-popupinfo-documentation)
      (unless isled-editor-documents (error "Enabled preview did not load documentation"))
      (corfu-quit)
      ;; Reproduce add -> type -> choose -> RET -> space -> more prose.
      (goto-char (point-min))
      (search-forward "Add evidence")
      (backward-char 1)
      (execute-kbd-macro (kbd "RET"))
      (unless (= (point) (widget-field-start (cdr (assoc "evidence.0" isled-editor-fields))))
        (error "Add evidence did not focus its new field"))
      (setq corfu-auto t)
      (execute-kbd-macro (kbd "# W i d TAB C-n RET SPC m o r e"))
      (unless (string-match-p "\\`#[0-9]\\{4\\} more\\'" (isled-editor-form-value "evidence.0"))
        (error "Completion acceptance corrupted Evidence: %s" (isled-editor-form-value "evidence.0")))
      (when (isled-editor-completion-at-point)
        (error "Accepted reference still completes subsequent prose"))
      (goto-char (widget-field-start (cdr (assoc "title" isled-editor-fields))))
      (execute-kbd-macro (kbd "# W i d TAB C-n RET SPC f i x"))
      (unless (string-match-p "\\`#[0-9]\\{4\\} fix\\'" (isled-editor-form-value "title"))
        (error "Title reference completion failed"))
      (dolist (field '(waiting_on blocking))
        (goto-char (cdr (assq field isled-editor-add-buttons)))
        (execute-kbd-macro (kbd "RET"))
        (unless (= (point) (widget-field-start (cdr (assoc (format "%s.0.id" field) isled-editor-fields))))
          (error "Relation add did not focus its ID"))
        (execute-kbd-macro (kbd "TAB C-n RET"))
        (unless (string-match-p "\\`[0-9]\\{4\\}\\'" (isled-editor-form-value (format "%s.0.id" field)))
          (error "Empty relation completion failed"))
        (execute-kbd-macro (kbd "C-<tab> b e c a u s e"))
        (unless (equal (isled-editor-form-value (format "%s.0.reason" field)) "because")
          (error "Relation reason navigation failed"))
        (execute-kbd-macro (kbd "C-<tab> RET"))
        (unless (= (point) (cdr (assq field isled-editor-add-buttons)))
          (error "Relation removal lost section position")))
      (goto-char (widget-field-end (cdr (assoc "evidence.0" isled-editor-fields))))
      (execute-kbd-macro (kbd "C-<tab> RET"))
      (unless (= (point) (cdr (assq 'evidence isled-editor-add-buttons)))
        (error "Removing last Evidence lost section position"))
      ;; Mouse down/up must retain the action's destination, not the
      ;; pre-click point restored by the default widget mouse handler.
      (dolist (field '(evidence waiting_on blocking))
        (let ((target (cdr (assq field isled-editor-add-buttons))))
          (goto-char target)
          (recenter)
          (redisplay t)
          (let ((position (posn-at-point target)))
            (goto-char (point-min))
            (execute-kbd-macro (vector (list 'down-mouse-1 position) (list 'mouse-1 position)))))
        (let ((locator (format "%s.0%s" field (if (eq field 'evidence) "" ".id"))))
          (unless (= (point) (widget-field-start (cdr (assoc locator isled-editor-fields))))
            (error "Mouse Add lost focus for %s" field)))
        (search-forward (if (eq field 'evidence) "Remove evidence" "Remove relation"))
        (backward-char 1)
        (recenter)
        (redisplay t)
        (let ((position (posn-at-point)))
          (goto-char (point-min))
          (execute-kbd-macro (vector (list 'down-mouse-1 position) (list 'mouse-1 position))))
        (unless (= (point) (cdr (assq field isled-editor-add-buttons)))
          (error "Mouse Remove lost focus for %s" field)))
      (set-buffer-modified-p nil)
      (isled-editor-cleanup)
      (delete-file file)
      (with-temp-file (getenv "ISLED_GRAPHICAL_RESULT") (insert "passed\n"))
      (kill-emacs 0))
  (error
   (with-temp-file (getenv "ISLED_GRAPHICAL_RESULT") (insert (format "failed: %S\n" failure)))
   (kill-emacs 1)))
