;;; editor-graphical.el --- Private draft layout and keyboard check -*- lexical-binding: t; -*-
(require 'isled-editor)
(require 'color)
(setq inhibit-startup-screen t)
(condition-case failure
    (progn
      (switch-to-buffer (get-buffer-create "*Disposable ledger*"))
      (erase-buffer)
      (insert "Disposable issue ledger\n\n0123  Improve draft validation\n0124  Add field diagnostics\n")
      (let* ((window (split-window-right))
             (buffer (generate-new-buffer "*Draft layout check*")))
        (set-window-buffer window buffer)
        (select-window window)
        (with-current-buffer buffer
          (isled-editor-mode)
          (setq isled-editor-root temporary-file-directory)
          (let ((draft (isled-editor-empty-draft)))
            (setf (alist-get 'title draft) "Improve draft validation")
            (setf (alist-get 'statement draft) "Explain what needs to change and why.\n\nOrdinary Markdown with #references and links.")
            (setf (alist-get 'evidence draft) ["Reproduced with an empty title."])
            (isled-editor-form-render draft))
          (set-buffer-modified-p nil)
          (redisplay t)
          (let ((before (point)))
            (execute-kbd-macro (kbd "C-<tab>"))
            (unless (/= before (point)) (error "Field navigation did not move"))
            (execute-kbd-macro (kbd "C-S-<iso-lefttab>"))
            (unless (= before (point)) (error "Reverse field navigation did not return")))
          (let ((value (isled-editor-form-value "title")))
            (execute-kbd-macro (kbd "TAB"))
            (unless (equal value (isled-editor-form-value "title"))
              (error "TAB changed the title")))
          (isled-editor-form-errors [((field . "title") (message . "Copy this diagnostic"))])
          (goto-char (point-min))
          (search-forward "Copy this diagnostic")
          (execute-kbd-macro (kbd "C-a"))
          (unless (= (current-column) 0) (error "Motion constrained on error line"))
          (let ((editor-window (selected-window)) (ledger-window (previous-window)))
            (execute-kbd-macro (kbd "C-c ?"))
            (unless (transient-active-prefix 'isled-editor-help)
              (error "Help did not open a Transient"))
            (unless (and (window-live-p editor-window) (window-live-p ledger-window)
                         (get-buffer-window transient--buffer))
              (error "Transient help lost its windows"))
            (execute-kbd-macro (kbd "q")))
          (goto-char (widget-field-start (cdr (assoc "title" isled-editor-fields))))
          (isled-editor-form-highlight)
          (dolist (theme '(wombat tango))
            (mapc #'disable-theme custom-enabled-themes)
            (load-theme theme t)
            (dolist (face '(isled-editor-field isled-editor-active-field))
              (let ((fg (face-foreground face nil t)) (bg (face-background face nil t)))
                (unless (> (color-distance fg bg) 10000)
                  (error "Low field contrast: %S %s %s" face fg bg))))
            (redisplay t)
            (when-let ((file (getenv "ISLED_EDITOR_SCREENSHOT")))
              (with-temp-file (concat file "-" (symbol-name theme) ".png")
                (set-buffer-multibyte nil)
                (insert (x-export-frames nil 'png)))))
          (when-let ((file (getenv "ISLED_EDITOR_SCREENSHOT")))
            (with-temp-file file
              (set-buffer-multibyte nil)
              (insert (x-export-frames nil 'png))))
          (set-buffer-modified-p nil)))
      (with-temp-file (getenv "ISLED_GRAPHICAL_RESULT") (insert "passed\n"))
      (kill-emacs 0))
  (error
   (with-temp-file (getenv "ISLED_GRAPHICAL_RESULT")
     (insert (format "failed: %S\n" failure)))
   (kill-emacs 1)))
