;;; isled-graph-test.el --- Dependency graph behavior tests -*- lexical-binding: t; -*-

;;; Commentary:
;; Exercise malformed layouts, sparse painting, view transitions and the real
;; Rust request boundary without contacting a working Emacs session.

;;; Code:
(require 'isled-browser)
(require 'isled-view-test)
(require 'isled-loading-test)

(defun isled-graph-test--diamond ()
  "Return the canonical four-row diamond layout."
  '((lanes . 3)
    (rows . (((filtered_prerequisites . 0) (filtered_dependents . 0) (id . "0001") (lane . 0) (start . :json-null) (targets . (1 2)))
             ((filtered_prerequisites . 0) (filtered_dependents . 0) (id . "0002") (lane . 1) (start . 0) (targets . (3)))
             ((filtered_prerequisites . 0) (filtered_dependents . 0) (id . "0003") (lane . 2) (start . 0) (targets . (3)))
             ((filtered_prerequisites . 0) (filtered_dependents . 0) (id . "0004") (lane . 1) (start . 1) (targets . nil))))))

(ert-deftest isled-graph-validates-lanes-routes-and-identities ()
  (let ((plan (isled-graph--decode-plan (isled-graph-test--diamond))))
    (should (equal (isled-graph-continuing plan 0) nil))
    (should (equal (isled-graph-continuing plan 1) '(1 2)))
    (should (equal (isled-graph-continuing plan 3) '(1)))
    (should (equal (isled-graph-continuing plan 4) nil)))
  (dolist (mutation '((0 id "0000") (1 id "0001") (0 lane 3)
                       (0 targets (1 1)) (0 targets (4)) (1 targets (0))
                       (3 start 0) (2 lane 1) (0 filtered_prerequisites -1)
                       (0 filtered_dependents :json-null) (0 filtered_dependents 9999)))
    (let* ((wire (copy-tree (isled-graph-test--diamond)))
           (row (nth (car mutation) (alist-get 'rows wire))))
      (setf (alist-get (cadr mutation) row) (nth 2 mutation))
      (should-error (isled-graph--decode-plan wire) :type 'isled-snapshot-error))))

(ert-deftest isled-graph-gutters-distinguish-joins-and-continue-through-bodies ()
  (isled-loading-test--with-displayed-buffer
    (isled-mode)
    (setq isled--snapshot (isled-view-test--open-snapshot "0001" "0002" "0003" "0004")
          isled-graph-direction 'prerequisites isled-graph-hash "0000000000000001"
          isled-graph-layout (isled-graph--decode-plan (isled-graph-test--diamond)))
    (isled--render)
    (cl-letf (((symbol-function 'isled-windows-visible) (lambda () (list (selected-window)))))
      (isled-graph-gutter-update))
    (should (equal (substring-no-properties (isled-graph-glyphs-heading (isled-graph-gutter--strings 0))) "○      "))
    (should (equal (substring-no-properties (isled-graph-glyphs-connector (isled-graph-gutter--strings 2))) "  ├─╯  "))
    (let ((plan isled-graph-layout) (row (aref isled-rows 1)))
      (isled-sections-show row)
      (should (string-prefix-p "  │ │  " (get-text-property
                                           (1+ (isled-row-content row)) 'wrap-prefix)))
      (should (eq plan isled-graph-layout))
      (isled-sections-hide row)
      ;; Invisible body prefixes must not indent or replace the next circle.
      (should-not (get-text-property (isled-row-content row) 'line-prefix))
      (should-not (get-text-property (isled-row-content row) 'wrap-prefix))
      (let ((next (aref isled-rows 2)))
        (should (equal (substring-no-properties
                        (overlay-get (isled-row-heading-background next) 'before-string))
                       "  │ ○  ")))
      (should-not (overlay-get (isled-row-heading-background row) 'after-string))
      ;; Repeated styling neither duplicates graph strings nor changes row text.
      (let ((text (buffer-string))
            (before (overlay-get (isled-row-heading-background row) 'before-string)))
        (isled-graph-gutter-style row)
        (should (equal text (buffer-string)))
        (should (equal before (overlay-get (isled-row-heading-background row) 'before-string))))
      (should (eq plan isled-graph-layout))
      (should (equal (mapcar #'isled-row-value (append isled-rows nil))
                     '("0001" "0002" "0003" "0004"))))))

(ert-deftest isled-graph-gutter-painting-is-bounded-and-releases-offscreen-strings ()
  (isled-loading-test--with-displayed-buffer
    (isled-mode)
    (let* ((count 5000)
           (ids (mapcar (lambda (n) (format "%04d" n)) (number-sequence 1 count)))
           (wire `((lanes . 2)
                   (rows . ,(cl-loop for id in ids for index from 0
                                    collect `((filtered_prerequisites . 0) (filtered_dependents . 0) (id . ,id) (lane . ,(if (zerop index) 0 1))
                                              (start . ,(if (zerop index) :json-null (1- index)))
                                              (targets . ,(when (< (1+ index) count)
                                                            (list (1+ index))))))))))
      (setq isled--snapshot (apply #'isled-view-test--open-snapshot ids)
            isled-graph-direction 'prerequisites isled-graph-hash "0000000000000001"
            isled-graph-layout (isled-graph--decode-plan wire))
      (isled--render)
      (cl-letf (((symbol-function 'isled-windows-visible) (lambda () (list (selected-window))))
                ((symbol-function 'window-body-height) (lambda (&rest _) 10)))
        (isled-graph-gutter-update)
        (should (<= (hash-table-count isled-graph-gutter--painted) 60))
        (let ((first (aref isled-rows 0)))
          (goto-char (isled-row-start (aref isled-rows 2500)))
          (set-window-start (selected-window) (point))
          (isled-graph-gutter-update)
          (should (<= (hash-table-count isled-graph-gutter--painted) 60))
          (should-not (gethash first isled-graph-gutter--painted))
          (should (= (length (overlay-get (isled-row-heading-background first) 'before-string)) 1))
          ;; Offscreen placeholders preserve the same number of routing rows.
          (should (equal (buffer-substring-no-properties (isled-row-heading-end first)
                                                         (isled-row-content first)) " \n"))
          (should (= (length (get-text-property (isled-row-heading-end first) 'display)) 1))
          (should-not (overlay-get (isled-row-heading-background first) 'after-string)))))))

(ert-deftest isled-graph-missing-layout-keeps-the-last-good-view ()
  (isled-loading-test--with-displayed-buffer
    (isled-mode)
    (let* (call (isled-process-function
                (lambda (_dir request callback) (setq call (list request callback)))))
      (isled-loading-request 'refresh)
      (isled-loading-test--reply call 'refresh)
      (let ((text (buffer-string)))
        (isled-graph-reverse)
        (funcall (cadr call) (isled-command-result-create
                             :status 0 :stderr "" :stdout (isled-loading-test--wire 'view)))
        (should (eq isled-graph-direction 'prerequisites))
        (should (equal text (buffer-string)))
        (should (string-match-p "update the Isled CLI" isled--auto-revert-error))))))

(ert-deftest isled-graph-rapid-reverse-discards-the-in-flight-layout ()
  (isled-loading-test--with-displayed-buffer
    (isled-mode)
    (let* (call (isled-process-function
                (lambda (_dir request callback) (setq call (list request callback)))))
      (isled-loading-request 'refresh)
      (isled-loading-test--reply call 'refresh)
      (isled-graph-reverse)
      (let ((old call))
        (isled-graph-reverse)
        (should (eq isled-loading-graph-intent 'prerequisites))
        ;; An obsolete malformed graph reply must never reach validation.
        (funcall (cadr old) (isled-command-result-create :status 0 :stdout "bad" :stderr ""))
        (isled-loading-test--reply call 'view)
        (should (eq isled-graph-direction 'prerequisites))
        (should-not isled--auto-revert-error)))))

(ert-deftest isled-graph-rapid-toggle-discards-the-in-flight-view ()
  (isled-loading-test--with-displayed-buffer
    (isled-mode)
    (let* (call (isled-process-function
                (lambda (_dir request callback) (setq call (list request callback)))))
      (isled-loading-request 'refresh)
      (isled-loading-test--reply call 'refresh)
      (isled-graph-toggle)
      (should-not (alist-get 'graph (json-parse-string (car call) :object-type 'alist)))
      (let ((old call))
        (isled-graph-toggle)
        (should (eq isled-loading-graph-intent 'prerequisites))
        (funcall (cadr old) (isled-command-result-create :status 0 :stdout "bad" :stderr ""))
        (isled-loading-test--reply call 'view)
        (should (eq isled-graph-direction 'prerequisites))
        (should-not isled--auto-revert-error)))))

(ert-deftest isled-graph-overflow-restores-wrapping-after-resize-or-narrower-filter ()
  (isled-loading-test--with-displayed-buffer
    (isled-mode)
    (setq isled-graph-direction 'prerequisites
          isled-graph-layout (make-isled-graph-plan :lanes 50))
    (cl-letf (((symbol-function 'window-body-width) (lambda (&rest _) 80)))
      (isled-graph-gutter-overflow)
      (should truncate-lines))
    (cl-letf (((symbol-function 'window-body-width) (lambda (&rest _) 120)))
      (isled-graph-gutter-overflow)
      (should-not truncate-lines))
    (cl-letf (((symbol-function 'window-body-width) (lambda (&rest _) 80)))
      (isled-graph-gutter-overflow)
      (setq isled-graph-layout (make-isled-graph-plan :lanes 1))
      (isled-graph-gutter-overflow)
      (should-not truncate-lines))))

(ert-deftest isled-graph-real-process-filter-reverse-and-hidden-connections ()
  (skip-unless isled-test-program)
  (let ((root (make-temp-file "isled-graph-test-" t))
        (isled-program isled-test-program)
        (isled-process-function #'isled-process-start)
        (isled-auto-revert nil))
    (unwind-protect
        (progn
          (dolist (args '(("init") ("add" "Dependent" "Needle body." "--kind" "feature" "--tag" "rust")
                           ("add" "Prerequisite" "Other body." "--kind" "bug")
                           ("wait" "add" "1" "2" "Required")))
            (should (zerop (apply #'call-process isled-program nil nil nil "--root" root args))))
          (isled-loading-test--with-displayed-buffer
            (isled-mode)
            (setq default-directory (file-name-as-directory root))
            (isled-loading-request 'refresh)
            (isled-loading-test--await)
            (should-not isled--auto-revert-error)
            (should (eq isled-graph-direction 'prerequisites))
            (should (equal (mapcar #'isled-row-value (append isled-rows nil)) '("0002" "0001")))
            (isled-sections-goto-id "0001")
            (isled-sections-show (gethash "0001" isled-rows-index))
            (isled-loading-test--await)
            (isled-graph-toggle)
            (isled-loading-test--await)
            (should-not isled--auto-revert-error)
            (should-not isled-graph-direction)
            (should (equal (mapcar #'isled-row-value (append isled-rows nil)) '("0001" "0002")))
            (should (equal (isled-sections-id-at-point) "0001"))
            (should (equal (isled-sections-expanded-ids) '("0001")))
            (should (equal (isled-graph-header-filter isled--filter) "s:open · flat"))
            (should-error (isled-graph-reverse) :type 'user-error)
            (isled-filter--request "s:open needle t:rust")
            (isled-loading-test--await)
            (should-not isled-graph-direction)
            (isled-graph-toggle)
            (isled-loading-test--await)
            (should-not isled--auto-revert-error)
            (should (eq isled-graph-direction 'prerequisites))
            (should (equal isled--filter "s:open needle t:rust"))
            (should (= 1 (length isled-rows)))
            (should (equal (isled-sections-id-at-point) "0001"))
            (should (string-match-p "#0001  \\[feature\\] Dependent\n" (buffer-string)))
            (should-not (string-match-p "filtered" (buffer-string)))
            (should (string-prefix-p "○" (isled-graph-glyphs-heading
                                           (isled-graph-glyphs-render isled-graph-layout 0))))
            (should (equal (isled-sections-expanded-ids) '("0001")))
            (isled-sections-hide (aref isled-rows 0))
            (isled-graph-reverse)
            (isled-loading-test--await)
            (should-not isled--auto-revert-error)
            (should (eq isled-graph-direction 'dependents))
            (should (equal isled--filter "s:open needle t:rust"))
            (should (= 1 (length isled-rows)))
            (should-not (string-match-p "filtered" (buffer-string)))
            (let ((plan isled-graph-layout)
                  (source (current-buffer)) duplicate)
              (unwind-protect
                  (progn
                    (setq duplicate (isled-duplicate-view))
                    (should (eq isled-graph-direction 'dependents))
                    (should (eq plan isled-graph-layout))
                    (should (equal isled--filter "s:open needle t:rust")))
                (when (buffer-live-p duplicate) (kill-buffer duplicate))
                (switch-to-buffer source)))
            (isled-graph-toggle)
            (isled-loading-test--await)
            (should-not isled-graph-direction)
            (isled-filter-closed)
            (isled-loading-test--await)
            (should-not isled--auto-revert-error)
            (should (= 0 (length isled-rows)))
            (should-not isled-graph-direction)
            (isled-filter-all)
            (isled-loading-test--await)
            (should (= 1 (length isled-rows)))
            (should-not isled-graph-direction)
            (isled-graph-toggle)
            (isled-loading-test--await)
            (should (eq isled-graph-direction 'dependents))
            (should (equal isled--filter "needle t:rust"))
            (isled-filter--request "")
            (isled-loading-test--await)
            (should-not isled--auto-revert-error)
            (should (= 2 (length isled-rows)))
            (should-not (string-match-p "filtered" (buffer-string)))
            (should (equal (mapcar #'isled-row-value (append isled-rows nil)) '("0001" "0002")))))
      (delete-directory root t))))

(ert-deftest isled-graph-cut-threads-retain-circles-and-semantic-counts ()
  (let* ((wire '((lanes . 1)
                 (rows . (((id . "0001") (lane . 0) (start . :json-null) (targets . nil)
                           (filtered_prerequisites . 1) (filtered_dependents . 2))
                          ((id . "0002") (lane . 0) (start . :json-null) (targets . nil)
                           (filtered_prerequisites . 0) (filtered_dependents . 0))))))
         (isled-graph-layout (isled-graph--decode-plan wire)))
    (let ((row (aref (isled-graph-plan-rows isled-graph-layout) 0)))
      (should (= (isled-graph-row-filtered-prerequisites row) 1))
      (should (= (isled-graph-row-filtered-dependents row) 2)))
    (should (equal (isled-graph-glyphs-heading (isled-graph-glyphs-render isled-graph-layout 0)) "○  "))
    (should (equal (isled-graph-glyphs-heading (isled-graph-glyphs-render isled-graph-layout 1)) "•  "))
    (setf (alist-get 'filtered_prerequisites (car (alist-get 'rows wire))) nil)
    (should-error (isled-graph--decode-plan wire) :type 'isled-snapshot-error)))

(provide 'isled-graph-test)
;;; isled-graph-test.el ends here
