;;; isled-jump-test.el --- Direct issue selection tests -*- lexical-binding: t; -*-
;;; Commentary:
;; Exercise completion, shared history and delayed request cancellation.
;;; Code:
(require 'ert)
(require 'isled-browser)
(require 'isled-loading-test)
(require 'isled-view-test)

(ert-deftest isled-jump-completes-titles-and-normalizes-short-ids ()
  (let* ((issue (isled-issue-create :id "0012" :title "Hidden destination" :status "closed"))
         (completion-styles '(basic))
         (completion-category-defaults nil)
         (completion-category-overrides nil))
    (cl-letf (((symbol-function 'completing-read)
               (lambda (_prompt table &rest _)
                 (should (completion-all-completions "destination" table nil 11))
                 (should (equal (try-completion "#12" table) "0012 — Hidden destination"))
                 "#12")))
      (should (eq (isled-jump--read (list issue)) issue)))
    (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) "9999")))
      (should-error (isled-jump--read (list issue)) :type 'user-error))
    (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) (signal 'quit nil))))
      (should (eq (condition-case nil (isled-jump--read (list issue))
                    (quit 'cancelled)) 'cancelled)))))

(ert-deftest isled-jump-reveals-filtered-destination-through-shared-history ()
  (isled-loading-test--with-displayed-buffer
    (isled-mode)
    (let ((isled-loading-active nil)
          calls)
      (setq isled--snapshot (isled-view-test--snapshot)
            isled--root "/tmp/example" isled--filter 'open isled--selected-id "0001")
      (isled--render)
      (isled-sections-goto-id "0001")
      (forward-char 2)
      (let ((origin (isled-sections-point-state))
            (isled-process-function (lambda (_root request callback) (push (list request callback) calls))))
        (isled-jump-to-issue)
        (should (equal (alist-get 'status (alist-get 'filter (json-parse-string (caar calls) :object-type 'alist))) "all"))
        (cl-letf (((symbol-function 'isled-frontend-decode)
                   (lambda (_) (isled-response-create :root "/tmp/example" :view isled--snapshot)))
                  ((symbol-function 'completing-read) (lambda (&rest _) "2")))
          (funcall (cadar calls) (isled-command-result-create :status 0 :stdout "")))
        (should (equal (isled-sections-id-at-point) "0002"))
        (should (eq isled--filter 'closed))
        (should-not (isled-row-hidden (isled-row-at)))
        (isled-history-back)
        (should (eq isled--filter 'open))
        (should (equal origin (isled-sections-point-state)))))))

(ert-deftest isled-jump-late-and-superseded-replies-do-not-prompt ()
  (isled-loading-test--with-displayed-buffer
    (isled-mode)
    (setq isled--root "/tmp/example")
    (let ((inhibit-read-only t)) (insert "Some text"))
    (goto-char (point-min))
    (let* (calls prompted
           (isled-process-function (lambda (_root _request callback) (push callback calls))))
      (cl-letf (((symbol-function 'isled-frontend-decode)
                 (lambda (_) (setq prompted t) (error "Unexpected prompt"))))
        (isled-jump-to-issue)
        (isled-jump-to-issue)
        (funcall (cadr calls) (isled-command-result-create :status 0))
        (should-not prompted)
        (forward-char 1)
        (funcall (car calls) (isled-command-result-create :status 0))
        (should-not prompted)))))

(ert-deftest isled-jump-cancel-and-failure-preserve-view-and-history ()
  (isled-loading-test--with-displayed-buffer
    (isled-mode)
    (let ((isled-loading-active nil))
      (setq isled--snapshot (isled-view-test--snapshot)
            isled--root "/tmp/example" isled--filter 'open isled--selected-id "0001")
      (isled--render)
      (isled-sections-goto-id "0001")
      (let ((state (isled--capture-view-state))
            (origin (isled-navigation-origin)))
        (cl-letf (((symbol-function 'isled-frontend-decode)
                   (lambda (_) (isled-response-create :root "/tmp/example" :view isled--snapshot)))
                  ((symbol-function 'completing-read) (lambda (&rest _) (signal 'quit nil))))
          (isled-jump--receive (isled-command-result-create :status 0) isled--root origin 0))
        (isled-jump--receive (isled-command-result-create :status 1 :stderr "Ledger unavailable")
                            isled--root origin 0)
        (should (equal state (isled--capture-view-state)))
        (isled-navigation-with-window (should-not isled--back-history))))))

(ert-deftest isled-jump-key-migration-preserves-user-bindings ()
  (let ((isled-mode-map (make-sparse-keymap)) (isled--mode-map-version 3))
    (isled--migrate-mode-map)
    (should (eq (keymap-lookup isled-mode-map "j") #'isled-jump-to-issue))
    (keymap-unset isled-mode-map "j")
    (isled--migrate-mode-map)
    (should-not (keymap-lookup isled-mode-map "j"))
    (setq isled--mode-map-version 3)
    (keymap-set isled-mode-map "j" #'ignore)
    (isled--migrate-mode-map)
    (should (eq (keymap-lookup isled-mode-map "j") #'ignore))))

(provide 'isled-jump-test)
;;; isled-jump-test.el ends here
