;;; isled-listing-test.el --- Exclusive issue ordering tests -*- lexical-binding: t; -*-

;;; Commentary:
;; Exercise direct keys, complete queues and view memory through the real CLI.
;;; Code:
(require 'isled-loading-test)

(ert-deftest isled-listing-query-supports-orders-and-rejects-issue-limits ()
  (let ((criteria (isled-filter-query-criteria
                   "s:open w:awaiting-owner r:review o:oldest-first t:rust")))
    (should (equal (alist-get 'work_reason criteria) "review"))
    (should (eq (alist-get 'oldest_first criteria) t))
    (should-not (assq 'limit criteria))
    (should (equal (alist-get 'tags criteria) ["rust"])))
  (dolist (bad '("r:unknown" "o:date" "n:0" "n:3" "n:-1" "n:all"))
    (should-error (isled-filter-query-criteria bad) :type 'user-error))
  (should (equal (alist-get 'text (isled-filter-query-criteria "\"n:3\"")) ["n:3"]))
  (should (eq (isled-filter-query-order "\"o:oldest-first\" o:id") 'id))
  (should-not (isled-filter-query-order "\"o:oldest-first\"")))

(ert-deftest isled-listing-direct-key-agrees-with-the-help-menu ()
  (with-temp-buffer
    (isled-mode)
    (should (eq (key-binding (kbd "S")) #'isled-listing-order))
    (should (eq (plist-get (cdr (transient-get-suffix 'isled-help "S")) :command)
                #'isled-listing-order))
    (should-error (transient-get-suffix 'isled-help "L")))
  (should-not (fboundp 'isled-listing-limit)))

(ert-deftest isled-listing-rapid-choices-retain-the-last-selected-flat-order ()
  (isled-loading-test--with-displayed-buffer
    (isled-mode)
    (let* (call (isled-process-function
                (lambda (_root request callback) (setq call (list request callback)))))
      (isled-loading-request 'refresh)
      (isled-loading-test--reply call 'refresh)
      (isled-listing-order 'oldest-first)
      (let ((obsolete call))
        (isled-graph-toggle)
        (isled-graph-toggle)
        (should-not isled-loading-graph-intent)
        (should (eq (isled-filter-query-order isled-loading-intent) 'oldest-first))
        (funcall (cadr obsolete) (isled-command-result-create
                                 :status 0 :stdout "obsolete reply" :stderr ""))
        (isled-loading-test--reply call 'view)
        (should-not isled-graph-direction)
        (should (eq isled-listing-flat-order 'oldest-first))
        (should-not isled--auto-revert-error)))))

(ert-deftest isled-listing-real-orders-toggle-and-history-remain-exclusive ()
  (skip-unless isled-test-program)
  (let ((root (make-temp-file "isled-order-test-" t))
        (isled-program isled-test-program)
        (isled-process-function #'isled-process-start)
        (isled-auto-revert nil))
    (unwind-protect
        (progn
          (dolist (args '(("init")
                         ("add" "Later" "First body." "--kind" "feature")
                         ("add" "Earlier" "Second body." "--kind" "feature")
                         ("work" "queue" "1" "--at" "2026-10-06 10:00:00")
                         ("work" "queue" "2" "--at" "2026-10-06 09:00:00")
                         ("wait" "add" "2" "1" "Needed first.")))
            (should (zerop (apply #'call-process isled-program nil nil nil "--root" root args))))
          (isled-loading-test--with-displayed-buffer
            (isled-mode)
            (setq default-directory (file-name-as-directory root))
            (isled-loading-request 'refresh)
            (isled-loading-test--await)
            ;; The actual major-mode binding works before opening the help menu.
            (cl-letf (((symbol-function 'completing-read)
                       (lambda (_prompt choices &rest _)
                         (should (equal choices '("Hierarchy" "Issue ID" "Oldest first")))
                         "Oldest first")))
              (call-interactively (key-binding (kbd "S"))))
            (isled-loading-test--await)
            (should-not isled--auto-revert-error)
            (should-not isled-graph-direction)
            (should (= (length isled-rows) 2))
            (should (equal (mapcar #'isled-row-value (append isled-rows nil)) '("0002" "0001")))
            (isled-sections-goto-id "0002")
            (isled-sections-show (isled-row-at))
            (isled-loading-test--await)
            (search-forward "Second body.")
            (let ((point-state (isled-sections-point-state)))
              (isled-graph-toggle)
              (isled-loading-test--await)
              (should (eq isled-graph-direction 'prerequisites))
              (should-not (isled-filter-query-order isled--filter))
              (should (equal (mapcar #'isled-row-value (append isled-rows nil)) '("0001" "0002")))
              (should (equal point-state (isled-sections-point-state)))
              ;; Reversing hierarchy must not forget the last flat choice.
              (isled-graph-reverse)
              (isled-loading-test--await)
              (isled-graph-toggle)
              (isled-loading-test--await)
              (should-not isled-graph-direction)
              (should (eq (isled-filter-query-order isled--filter) 'oldest-first))
              (should (equal point-state (isled-sections-point-state))))
            (let ((saved (isled--capture-view-state)))
              (isled-listing-order 'id)
              (isled-loading-test--await)
              (should-not isled-graph-direction)
              (should (equal (mapcar #'isled-row-value (append isled-rows nil)) '("0001" "0002")))
              (isled-listing-order 'hierarchy)
              (isled-loading-test--await)
              (should (eq isled-graph-direction 'dependents))
              (should-not (isled-filter-query-order isled--filter))
              (isled-graph-toggle)
              (isled-loading-test--await)
              (should-not isled-graph-direction)
              (should (eq isled-listing-flat-order 'id))
              (isled--restore-view-state saved)
              (isled-loading-test--await)
              (should (eq isled-listing-flat-order 'oldest-first)))
            (isled-listing-order 'hierarchy)
            (isled-loading-test--await)
            (let ((source (current-buffer)) duplicate)
              (unwind-protect
                  (progn
                    (setq duplicate (isled-duplicate-view))
                    (isled-loading-test--await)
                    (should (eq isled-listing-flat-order 'oldest-first))
                    (isled-graph-toggle)
                    (isled-loading-test--await)
                    (should-not isled-graph-direction)
                    (should (eq (isled-filter-query-order isled--filter) 'oldest-first))
                    (should (buffer-local-value 'isled-graph-direction source)))
                (when (buffer-live-p duplicate) (kill-buffer duplicate))
                (switch-to-buffer source)))
            ;; Filter syntax also selects one flat mode, including a repeated term.
            (isled-listing-order 'hierarchy)
            (isled-loading-test--await)
            (isled-filter--request "s:open w:queued o:oldest-first")
            (isled-loading-test--await)
            (should-not isled-graph-direction)
            (isled-filter--request "s:open w:queued o:id")
            (isled-loading-test--await)
            (should-not isled-graph-direction)
            (should (eq isled-listing-flat-order 'id))
            (isled-filter--request "s:open w:queued o:oldest-first")
            (isled-loading-test--await)
            (isled-filter--request "s:open w:queued")
            (isled-loading-test--await)
            (should (eq isled-listing-flat-order 'id))
            (should-not isled--auto-revert-error)))
      (delete-directory root t))))

(provide 'isled-listing-test)
;;; isled-listing-test.el ends here
