;;; isled-filter-test.el --- Status view tests -*- lexical-binding: t; -*-

(require 'isled-browser)
(require 'isled-view-test)

(ert-deftest isled-all-retains-point-without-saving-an-all-view ()
  (with-temp-buffer
    (isled-mode)
    (setq isled--snapshot (isled-view-test--snapshot)
          isled--selected-id "0001"
          isled--expanded-ids '("0001"))
    (isled--render)
    (search-forward "Body.")
    (let ((origin (isled-sections-point-state)))
      (isled-filter-all)
      (should (= 2 isled--header-count))
      (should (equal origin (isled-sections-point-state)))
      (isled-filter-closed)
      (should (equal "0002" isled--selected-id))
      (isled-filter-all)
      (should (equal "0002" isled--selected-id))
      (isled-filter-open)
      (should (equal origin (isled-sections-point-state)))
      (should-not (assq 'all isled--saved-view-states))
      (should-not isled--back-history))))

(ert-deftest isled-all-to-status-retains-visible-point ()
  (with-temp-buffer
    (isled-mode)
    (setq isled--snapshot (isled-view-test--snapshot)
          isled--selected-id "0001")
    (isled--render)
    (isled-filter-all)
    (isled-sections-goto-id "0002")
    (isled-sections-show (isled-row-at))
    (search-forward "Done.")
    (let ((origin (isled-sections-point-state)))
      (isled-filter-closed)
      (should (equal origin (isled-sections-point-state)))
      (should (equal '("0002") (isled-sections-expanded-ids))))))

(ert-deftest isled-all-empty-selection ()
  (with-temp-buffer
    (isled-mode)
    (setq isled--snapshot (isled-view-test--snapshot))
    (setf (isled-snapshot-issues isled--snapshot) nil)
    (isled--render)
    (isled-filter-all)
    (should-not isled--selected-id)
    (should (zerop isled--header-count))))

(ert-deftest isled-all-reference-history-and-refresh ()
  (with-temp-buffer
    (isled-mode)
    (setq isled--snapshot (isled-view-test--snapshot)
          isled--selected-id "0001"
          isled--expanded-ids '("0001"))
    (isled--render)
    (isled-filter-all)
    (search-forward "#0002")
    (backward-char)
    (let ((origin (isled-sections-point-state)))
      (isled-jump-to-reference)
      (should (eq 'all isled--filter))
      (should (equal "0002" isled--selected-id))
      (isled-filter-closed)
      (isled-history-back)
      (should (eq 'all isled--filter))
      (should (equal origin (isled-sections-point-state)))
      (cl-letf (((symbol-function 'isled--load-snapshot)
                 (lambda (_) isled--snapshot)))
        (isled--revert-buffer))
      (should (equal origin (isled-sections-point-state)))
      (isled-history-forward)
      (should (eq 'closed isled--filter))
      (should (equal "0002" isled--selected-id))
      (should-not (assq 'all isled--saved-view-states)))))

(ert-deftest isled-status-defaults-use-explicit-filter-commands ()
  (with-temp-buffer
    (isled-mode)
    (should (eq isled--filter 'open))
    (should (eq (key-binding (kbd "f")) #'isled-filter))
    (should (eq (key-binding (kbd "a")) #'isled-add-issue))
    (dolist (key '("o"))
      (should-not (keymap-lookup isled-mode-map key))
      (should-error (transient-get-suffix 'isled-help key))))
  (dolist (command '(isled-filter-open
                     isled-filter-closed isled-filter-all))
    (should (commandp command))))

(ert-deftest isled-status-commands-retain-other-query-criteria ()
  (with-temp-buffer
    (isled-mode)
    (setq isled--filter "s:open t:rust k:bug words")
    (cl-letf (((symbol-function 'isled--restore-view-state)
               (lambda (state &optional _callback)
                 (setq isled--filter
                       (isled--view-state-filter state)))))
      (dolist (choice '((isled-filter-closed . "closed")
                        (isled-filter-all . "all")
                        (isled-filter-open . "open")))
        (call-interactively (car choice))
        (let ((criteria (isled-filter-query-criteria isled--filter)))
          (should (equal (alist-get 'status criteria) (cdr choice)))
          (should (equal (alist-get 'tags criteria) ["rust"]))
          (should (equal (alist-get 'kinds criteria) ["bug"]))
          (should (equal (alist-get 'text criteria) ["words"])))))))

(ert-deftest isled-status-reload-retires-only-old-defaults ()
  (let ((isled-mode-map (copy-keymap isled-mode-map))
        (isled--mode-map-version 0))
    (dolist (binding '(("o" . isled-filter-open)
                       ("c" . isled-filter-closed)
                       ("a" . isled-filter-all)))
      (keymap-set isled-mode-map (car binding) (cdr binding)))
    (load "isled-browser" nil t)
    (dolist (key '("o" "c"))
      (should-not (keymap-lookup isled-mode-map key)))
    (keymap-set isled-mode-map "o" #'ignore)
    (keymap-set isled-mode-map "c" #'isled-filter-all)
    (keymap-unset isled-mode-map "a")
    (load "isled-browser" nil t)
    (should (eq (keymap-lookup isled-mode-map "o") #'ignore))
    (should (eq (keymap-lookup isled-mode-map "c")
                #'isled-filter-all))
    (should-not (keymap-lookup isled-mode-map "a"))))

(provide 'isled-filter-test)
;;; isled-filter-test.el ends here
