;;; isled-keymap-test.el --- Issue mode key customization -*- lexical-binding: t; -*-

;;; Commentary:
;; Verify one-time defaults, migration, reloads, and honest help hints.

;;; Code:

(require 'ert)
(require 'isled-browser)

(ert-deftest isled-keymap-reload-preserves-personal-configuration ()
  (let ((isled-mode-map (copy-keymap isled-mode-map))
        (isled--mode-map-version 1)
        (parent (make-sparse-keymap)))
    (set-keymap-parent isled-mode-map parent)
    (keymap-set isled-mode-map "r" #'isled-refresh)
    (keymap-unset isled-mode-map "g")
    (keymap-set isled-mode-map
                "<remap> <isled-next>" #'next-line)
    (load "isled" nil t)
    (load "isled-browser" nil t)
    (should (eq (keymap-parent isled-mode-map) parent))
    (should (eq (keymap-lookup isled-mode-map "r")
                #'isled-refresh))
    (should-not (keymap-lookup isled-mode-map "g"))
    (should (eq (lookup-key isled-mode-map
                            [remap isled-next])
                #'next-line))))

(ert-deftest isled-keymap-migration-runs-only-once ()
  (let ((isled-mode-map (copy-keymap isled-mode-map))
        (isled--mode-map-version 0))
    (dolist (binding '(("o" . isled-filter-open)
                       ("c" . isled-filter-closed)
                       ("a" . isled-filter-all)
                       ("s" . isled-search)))
      (keymap-set isled-mode-map (car binding) (cdr binding)))
    (isled--migrate-mode-map)
    (dolist (key '("o" "c" "s"))
      (should-not (keymap-lookup isled-mode-map key)))
    (should (= isled--mode-map-version 8))
    (keymap-set isled-mode-map "o" #'isled-filter-open)
    (keymap-unset isled-mode-map "f")
    (isled--migrate-mode-map)
    (should (eq (keymap-lookup isled-mode-map "o")
                #'isled-filter-open))
    (should-not (keymap-lookup isled-mode-map "f"))))

(ert-deftest isled-keymap-entry-preserves-a-user-predefined-map ()
  (let ((isled-mode-map (copy-keymap isled-mode-map))
        (isled--mode-map-version 1)
        (original-featurep (symbol-function 'featurep)))
    (keymap-set isled-mode-map "o" #'isled-filter-open)
    (makunbound 'isled--mode-map-version)
    (cl-letf (((symbol-function 'featurep)
               (lambda (feature)
                 (if (eq feature 'isled-browser) nil
                   (funcall original-featurep feature)))))
      (load "isled" nil t))
    (should (= isled--mode-map-version 8))
    (load "isled-browser" nil t)
    (should (= isled--mode-map-version 8))
    (should (eq (keymap-lookup isled-mode-map "o")
                #'isled-filter-open))))

(ert-deftest isled-keymap-entry-detects-an-old-loaded-browser ()
  (let ((isled-mode-map (copy-keymap isled-mode-map))
        (isled--mode-map-version 1))
    (keymap-set isled-mode-map "o" #'isled-filter-open)
    (makunbound 'isled--mode-map-version)
    (load "isled" nil t)
    (should (= isled--mode-map-version 0))
    (load "isled-browser" nil t)
    (should (= isled--mode-map-version 8))
    (should-not (keymap-lookup isled-mode-map "o"))))

(ert-deftest isled-keymap-warning-jump-installs-once-and-preserves-overrides ()
  (let ((isled-mode-map (make-sparse-keymap))
        (isled--mode-map-version 2))
    (isled--migrate-mode-map)
    (should (eq (keymap-lookup isled-mode-map "!") #'isled-jump-to-warning))
    (keymap-unset isled-mode-map "!")
    (isled--migrate-mode-map)
    (should-not (keymap-lookup isled-mode-map "!"))
    (setq isled--mode-map-version 2)
    (keymap-set isled-mode-map "!" #'ignore)
    (isled--migrate-mode-map)
    (should (eq (keymap-lookup isled-mode-map "!") #'ignore))))

(ert-deftest isled-help-hint-follows-the-mode-map ()
  (let ((isled-mode-map (copy-keymap isled-mode-map)))
    (keymap-unset isled-mode-map "?")
    (keymap-set isled-mode-map "H" #'isled-help)
    (should (equal (substring-no-properties (isled--fontified-help))
                   "[H] Help"))
    (keymap-unset isled-mode-map "H")
    (should (equal (substring-no-properties (isled--fontified-help))
                   "[M-x isled-help] Help"))))

(ert-deftest isled-keymap-graph-bindings-preserve-owner-overrides ()
  (let ((isled-mode-map (make-sparse-keymap))
        (isled--mode-map-version 4))
    (keymap-set isled-mode-map "v" #'ignore)
    (isled--migrate-mode-map)
    (should (eq (keymap-lookup isled-mode-map "v") #'ignore))
    (should (eq (keymap-lookup isled-mode-map "d") #'isled-graph-reverse))
    (keymap-unset isled-mode-map "d")
    (isled--migrate-mode-map)
    (should-not (keymap-lookup isled-mode-map "d"))))

(ert-deftest isled-keymap-restores-presentation-toggle-without-find ()
  (let ((isled-mode-map (make-sparse-keymap)) (isled--mode-map-version 5))
    (keymap-set isled-mode-map "v" #'isled-graph-toggle)
    (keymap-set isled-mode-map "M-n" #'isled-graph-next-match)
    (keymap-set isled-mode-map "M-p" #'ignore)
    (isled--migrate-mode-map)
    (should (eq (keymap-lookup isled-mode-map "v") #'isled-graph-toggle))
    (should-not (keymap-lookup isled-mode-map "M-n"))
    (should (eq (keymap-lookup isled-mode-map "M-p") #'ignore))))

(ert-deftest isled-keymap-presentation-toggle-installs-once ()
  (let ((isled-mode-map (make-sparse-keymap)) (isled--mode-map-version 6))
    (isled--migrate-mode-map)
    (should (eq (keymap-lookup isled-mode-map "v") #'isled-graph-toggle))
    (keymap-unset isled-mode-map "v")
    (isled--migrate-mode-map)
    (should-not (keymap-lookup isled-mode-map "v"))
    (setq isled--mode-map-version 6)
    (keymap-set isled-mode-map "v" #'ignore)
    (isled--migrate-mode-map)
    (should (eq (keymap-lookup isled-mode-map "v") #'ignore))))

(provide 'isled-keymap-test)
;;; isled-keymap-test.el ends here
