;;; isled-warnings-test.el --- Known warning navigation tests -*- lexical-binding: t; -*-
;;; Commentary:
;; Exercise normal history, unavailable records, wire decoding and header actions.
;;; Code:
(require 'ert)
(require 'isled-browser)
(require 'isled-view-test)
(require 'isled-recovery-test)

(ert-deftest isled-warnings-jump-reveals-closed-issue-and-back-restores-origin ()
  (save-window-excursion
    (with-temp-buffer
      (switch-to-buffer (current-buffer))
      (isled-mode)
      (let* ((isled-loading-active nil)
             (snapshot (isled-view-test--snapshot))
             (target (cadr (isled-snapshot-issues snapshot))))
        (setf (isled-issue-warnings target)
              (list (isled-recovery-test--warning "0099")))
        (setq isled--snapshot snapshot isled--root "/tmp/example"
              isled--filter 'open isled--selected-id "0001"
              isled-warnings-target target)
        (isled--render)
        (isled-sections-goto-id "0001")
        (forward-char 2)
        (let ((origin (isled-sections-point-state)))
          (isled-jump-to-warning)
          (should (eq isled--filter 'closed))
          (should (equal (isled-sections-id-at-point) "0002"))
          (should (eql (get-text-property (point) 'isled-warning-index) 0))
          (isled-history-back)
          (should (eq isled--filter 'open))
          (should (equal (isled-sections-point-state) origin)))))))

(ert-deftest isled-warnings-cycle-within-issues-across-filters-and-wrap ()
  (save-window-excursion
    (with-temp-buffer
      (switch-to-buffer (current-buffer))
      (isled-mode)
      (let* ((isled-loading-active nil)
             (snapshot (isled-view-test--snapshot))
             (first (car (isled-snapshot-issues snapshot)))
             (second (cadr (isled-snapshot-issues snapshot))))
        (setf (isled-issue-warnings first)
              (list (isled-recovery-test--warning "0098")
                    (isled-recovery-test--warning "0099"))
              (isled-issue-warnings second)
              (list (isled-recovery-test--warning "0099")))
        (setq isled--snapshot snapshot isled--root "/tmp/example"
              isled--filter 'open isled--selected-id "0001"
              isled-warnings-target first isled-warnings-targets (list first second))
        (isled--render)
        (isled-sections-goto-id "0001")
        (dolist (destination '(("0001" . 0) ("0001" . 1) ("0002" . 0) ("0001" . 0)))
          (isled-jump-to-warning)
          (should (equal (isled-sections-id-at-point) (car destination)))
          (should (eql (get-text-property (point) 'isled-warning-index) (cdr destination))))
        (isled-history-back)
        (should (equal (isled-sections-id-at-point) "0002"))
        (should (eq isled--filter 'closed))
        (setq isled-warnings-target second isled-warnings-targets (list second))
        (let ((before (isled-navigation-with-window (copy-sequence isled--back-history))))
          (isled-jump-to-warning)
          (isled-jump-to-warning)
          (isled-navigation-with-window
            (should (equal before isled--back-history))))))))

(ert-deftest isled-warnings-unavailable-target-and-empty-state ()
  (save-window-excursion
    (with-temp-buffer
      (switch-to-buffer (current-buffer))
      (isled-mode)
      (let* ((isled-loading-active nil)
             (snapshot (isled-view-test--snapshot))
             (target (isled-unavailable-create :id "0003" :path "/tmp/example/.issues/0003-bad.md" :error "Malformed")))
        (setf (isled-snapshot-unavailable snapshot) (list target))
        (setq isled--snapshot snapshot isled--root "/tmp/example"
              isled--filter 'open isled--selected-id "0001"
              isled-warnings-target target)
        (isled--render)
        (isled-sections-goto-id "0001")
        (let ((origin (isled-sections-point-state)))
          (isled-jump-to-warning)
          (should (equal (get-text-property (point) 'isled-warning-id) "0003"))
          (isled-history-back)
          (should (equal (isled-sections-point-state) origin)))
        (isled-warnings-accept (isled-response-create))
        (should-not (isled-warnings-indicator))
        (should-error (isled-jump-to-warning) :type 'user-error)))))

(ert-deftest isled-warnings-unreadable-destinations-have-distinct-history ()
  (save-window-excursion
    (with-temp-buffer
      (switch-to-buffer (current-buffer))
      (isled-mode)
      (let* ((isled-loading-active nil)
             (snapshot (isled-view-test--snapshot))
             (first (isled-unavailable-create :id "0003" :error "Malformed"))
             (second (isled-unavailable-create :id "0004" :error "Unreadable")))
        (setf (isled-snapshot-unavailable snapshot) (list first second))
        (setq isled--snapshot snapshot isled--filter 'open
              isled-warnings-target first isled-warnings-targets (list first second))
        (isled--render)
        (isled-sections-goto-id "0001")
        (isled-jump-to-warning)
        (should (equal (get-text-property (point) 'isled-warning-id) "0003"))
        (isled-jump-to-warning)
        (should (equal (get-text-property (point) 'isled-warning-id) "0004"))
        (isled-history-back)
        (should (equal (get-text-property (point) 'isled-warning-id) "0003"))
        (isled-history-back)
        (should (equal (isled-sections-id-at-point) "0001"))))))

(ert-deftest isled-warnings-header-keeps-click-action ()
  (let* ((isled-warnings-target (isled-issue-create :id "0001"))
         (text (isled-warnings-indicator))
         (rendered (isled-header-mode-line text))
         (map (get-text-property 0 'keymap text)))
    (should (string-match-p "Known warnings" text))
    (should (eq (keymap-lookup map "<header-line> <mouse-1>")
                #'isled-warnings-click))
    (should (eq (plist-get (cddr (cadr rendered)) 'keymap) map))))

(ert-deftest isled-warnings-wire-keeps-filtered-out-target ()
  (let* ((wire (json-parse-string (isled-loading-test--wire 'view)
                                 :object-type 'alist :array-type 'array
                                 :null-object :json-null :false-object :json-false))
         (target (aref (alist-get 'issues (alist-get 'view wire)) 0)))
    (setf (alist-get 'first_warning wire) `((type . "issue") (issue . ,target)))
    (setf (alist-get 'warning_targets wire) (vector (alist-get 'first_warning wire)))
    (setf (alist-get 'issues (alist-get 'view wire)) [])
    (let ((response (isled-frontend-decode (json-serialize wire :null-object :json-null :false-object :json-false))))
      (should-not (isled-snapshot-issues (isled-response-view response)))
      (should (equal (isled-issue-id (isled-response-first-warning response)) "0001"))
      (should (equal (mapcar #'isled-issue-id (isled-response-warning-targets response)) '("0001"))))))

(ert-deftest isled-warnings-real-process-loads-destination-and-restores-text-filter ()
  (skip-unless isled-test-program)
  (let ((root (make-temp-file "isled-known-warnings-" t))
        (isled-program isled-test-program)
        (isled-process-function #'isled-process-start)
        (isled-auto-revert nil))
    (unwind-protect
        (progn
          (dolist (arguments '(("init") ("add" "Warned" "--kind" "feature" "Body.")
                               ("add" "Origin" "--kind" "bug" "Body.")
                               ("add" "Another" "--kind" "feature" "Body.")))
            (should (zerop (apply #'call-process isled-program nil nil nil
                                  "--root" root arguments))))
          (dolist (name '("0001-warned.md" "0003-another.md"))
            (let ((file (expand-file-name (concat ".issues/" name) root)))
            (with-temp-buffer
              (insert-file-contents file)
              (goto-char (point-min))
              (search-forward "\n\n## Statement")
              (goto-char (match-beginning 0))
              (insert "\n- **Waiting on:**\n  - #9999 — Missing\n    - **Reason:** Needed.")
              (write-region (point-min) (point-max) file nil 'silent))))
          (isled-loading-test--with-displayed-buffer
            (isled-mode)
            (setq default-directory (file-name-as-directory root)
                  isled--filter "k:bug")
            (isled-loading-request 'refresh)
            (isled-loading-test--await)
            (should-not isled--auto-revert-error)
            (should (equal (isled-issue-id isled-warnings-target) "0001"))
            (isled-sections-goto-id "0002")
            (forward-char 2)
            (let ((origin (isled-sections-point-state)))
              (isled-jump-to-warning)
              (isled-loading-test--await)
              (should-not isled--auto-revert-error)
              (should (equal (isled-sections-id-at-point) "0001"))
              (should (eql (get-text-property (point) 'isled-warning-index) 0))
              (isled-jump-to-warning)
              (isled-loading-test--await)
              (should (equal (isled-sections-id-at-point) "0003"))
              (isled-jump-to-warning)
              (isled-loading-test--await)
              (should (equal (isled-sections-id-at-point) "0001"))
              (isled-history-back)
              (isled-loading-test--await)
              (should (equal (isled-sections-id-at-point) "0003"))
              (isled-history-back)
              (isled-loading-test--await)
              (should (equal (isled-sections-id-at-point) "0001"))
              (isled-history-back)
              (isled-loading-test--await)
              (should (equal isled--filter "k:bug"))
              (should (equal (isled-sections-point-state) origin)))))
      (delete-directory root t))))

(provide 'isled-warnings-test)
;;; isled-warnings-test.el ends here
